package proyecto.conexion.sql.server;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pablo
 */
public class VentanaAgenda extends javax.swing.JFrame {
    private String accion, id_actualizar,urlOrigen,sql;
    private String mensaje,imgDestino,extension,genero,email,observaciones,imgbd;
    DefaultTableModel modelo;
    Conexion Conect;
    String campoconsulta;
    /**
     * Creates new form VentanaAgenda
     */
    public VentanaAgenda() {
        initComponents();
        this.setLocationRelativeTo(null);
        accion= "Insertar"; 
        id_actualizar="";
        urlOrigen="";
        sql="";
        observaciones="";
        cargarTabla("");
        deshabilitar();
        campoconsulta="";
        textfield_buscar.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textfield_nombre = new javax.swing.JTextField();
        textfield_apellido = new javax.swing.JTextField();
        textfield_departamento = new javax.swing.JTextField();
        textfield_direccion = new javax.swing.JTextField();
        textfield_secretaria = new javax.swing.JTextField();
        textfield_domicilio = new javax.swing.JTextField();
        textfield_telefono_oficina = new javax.swing.JTextField();
        textfield_telefono_celular = new javax.swing.JTextField();
        textfield_correo = new javax.swing.JTextField();
        textfield_observaciones = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        button_agregar = new javax.swing.JButton();
        button_guardar = new javax.swing.JButton();
        button_borrar = new javax.swing.JButton();
        button_cancelar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_consulta = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        textfield_buscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        combobox_parametro = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nombre");

        jLabel3.setText("Departamento");

        jLabel4.setText("Dirección");

        jLabel5.setText("Secretaría");

        jLabel6.setText("Domicilio");

        jLabel7.setText("Telefono Oficina");

        jLabel8.setText("Telefono Celular");

        jLabel9.setText("Correo Electrónico");

        jLabel10.setText("Observaciones");

        jLabel11.setText("Apellido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textfield_nombre)
                    .addComponent(textfield_apellido)
                    .addComponent(textfield_departamento)
                    .addComponent(textfield_direccion)
                    .addComponent(textfield_secretaria)
                    .addComponent(textfield_domicilio)
                    .addComponent(textfield_telefono_oficina)
                    .addComponent(textfield_telefono_celular)
                    .addComponent(textfield_correo)
                    .addComponent(textfield_observaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addGap(275, 275, 275))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textfield_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textfield_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textfield_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textfield_secretaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textfield_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textfield_telefono_oficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textfield_telefono_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textfield_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textfield_observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        button_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1490259852_add_user.png"))); // NOI18N
        button_agregar.setText("Agregar");
        button_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_agregarActionPerformed(evt);
            }
        });

        button_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1490260266_Save.png"))); // NOI18N
        button_guardar.setText("Guardar");
        button_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_guardarActionPerformed(evt);
            }
        });

        button_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1490260029_remove_user.png"))); // NOI18N
        button_borrar.setText("Borrar");
        button_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_borrarActionPerformed(evt);
            }
        });

        button_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1490260321_Close_Icon.png"))); // NOI18N
        button_cancelar.setText("Cancelar");
        button_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1490262575_Exit_Arrow_Door_Signout_Out_Close.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(button_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_agregar)
                .addComponent(button_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        table_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_consultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_consulta);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textfield_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_buscarActionPerformed(evt);
            }
        });
        textfield_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfield_buscarKeyReleased(evt);
            }
        });

        jLabel2.setText("Buscar");

        combobox_parametro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre", "Apellido", "Departamento", "Direccion", "Secretaria", "Domicilio", "Telefono_oficina", "Telefono_celular", "Correo", "Observaciones" }));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1490261946_Search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combobox_parametro, 0, 260, Short.MAX_VALUE)
                    .addComponent(textfield_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textfield_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combobox_parametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FINAGOBLOGO.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(1011, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Metodo que inserta y modifica los datos
    private void insertarModificar(){
         System.out.print("Empieza metodo modificar..."); 
        String nom,ape,dep,dir,sec,dom,telof,telcel,corr,observ;
        nom = textfield_nombre.getText();
        ape = textfield_apellido.getText();
        dep = textfield_departamento.getText();
        dir = textfield_direccion.getText();
        sec = textfield_secretaria.getText();
        dom = textfield_domicilio.getText();
        telof = textfield_telefono_oficina.getText();
        telcel = textfield_telefono_celular.getText();
        corr = textfield_correo.getText();
        observ = textfield_observaciones.getText();
        System.out.print("Previo a catch..."); 
        try {
            System.out.print("Previo a conexion..."); 
            Conect = new Conexion();
            System.out.print("Post conexion...");
            System.out.print("Accion: "+accion); 
            if(accion.equals("Insertar")){
                System.out.print("Estoy guardando nuevo...");
                sql= "INSERT INTO Contacto( Nombre,Apellido,Departamento,Direccion,Secretaria,Domicilio,Telefono_oficina,Telefono_celular,Correo,Observaciones,Imagen)"+" VALUES(?,?,?,?,?,?,?,?,?,?,?)";
                mensaje="Los datos se han insertado";
                //metodo deshabilitar controles
                deshabilitar();
            }
            
            if((accion.equals("Modificar"))){
                System.out.print("Estoy actualizando...");
                sql= "UPDATE Contacto SET Nombre = ?,Apellido = ?,Departamento = ?,Direccion = ?,Secretaria = ?, Domicilio = ?,Telefono_oficina = ?,Telefono_celular = ?,Correo = ?,Observaciones = ?,Imagen=? WHERE Id_Contacto = "+id_actualizar;
                mensaje="Los datos se han actualizado";
                //metodo deshabilitar controles
                deshabilitar();
            }
            PreparedStatement pst=Conect.conexion.prepareStatement(sql);
            imgDestino="Foto";
            pst.setString(1, nom);
            pst.setString(2, ape);
            pst.setString(3, dep);
            pst.setString(4, dir);
            pst.setString(5, sec);
            pst.setString(6, dom);
            pst.setString(7, telof);
            pst.setString(8, telcel);
            pst.setString(9, corr);
            pst.setString(10, observ);
            pst.setString(11, imgDestino);
            int n=pst.executeUpdate();
            if(n>0){
                JOptionPane.showMessageDialog(null, mensaje);
                //metodo cargar tabla
                cargarTabla("");
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
        }
        
    }
    
    private void button_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_agregarActionPerformed
        habilitar();
    }//GEN-LAST:event_button_agregarActionPerformed

    private void button_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelarActionPerformed
        deshabilitar();
    }//GEN-LAST:event_button_cancelarActionPerformed

    private void guardarImagenes(){
        String nombre=textfield_nombre.getText();
        if(urlOrigen.equals(" ")){
            extension =urlOrigen.substring(urlOrigen.lastIndexOf("."));
            imgDestino="C:\\Users\\Pablo\\Documents\\NetBeansProjects\\SISTEMA_FINAGOB\\src\\"+nombre+extension;
        }
        else{
            //eliminar imagenes duplicadas
            String png=".png",jpg=".jpg",imgEliminar="";
            imgDestino="C:\\Users\\Pablo\\Documents\\NetBeansProjects\\SISTEMA_FINAGOB\\src\\"+nombre+imgEliminar;
            File fichero;
            //Evaluar extension
            switch(extension){
                case ".jpg":
                    fichero= new File(imgEliminar+png);
                    if(fichero.exists()){
                        fichero.delete();
                    }
                    break;
                case ".png":
                    fichero= new File(imgEliminar+jpg);
                    if(fichero.exists()){
                        fichero.delete();
                    }
                    break;
                    
            }

        }
        try{
            FileInputStream fregis = new FileInputStream(urlOrigen);
            FileOutputStream fsalida = new FileOutputStream(imgDestino,true);
            int b=fregis.read();
            while(b!=-1){
                fsalida.write(b);
                b=fregis.read();
            }
            fsalida.flush();
            fsalida.close();
            fregis.close();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error al generar copia");
        }
        insertarModificar();
    }
    
    private void button_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_guardarActionPerformed
        if(textfield_nombre.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese nombre");
            textfield_nombre.requestFocus();
        }else{
            if(textfield_apellido.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese apellido");
            textfield_apellido.requestFocus();
            }else{
                if(textfield_departamento.getText().equals("")){
                 JOptionPane.showMessageDialog(null,"Ingrese departamento");
                textfield_departamento.requestFocus();
                }else{
                    if(textfield_direccion.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"Ingrese direccion");
                    textfield_direccion.requestFocus();
                    }else{
                        if(textfield_secretaria.getText().equals("")){
                        JOptionPane.showMessageDialog(null,"Ingrese secretaria");
                        textfield_secretaria.requestFocus();
                        }else{
                            if(textfield_domicilio.getText().equals("")){
                            JOptionPane.showMessageDialog(null,"Ingrese domicilio");
                            textfield_domicilio.requestFocus();
                            }else{
                                if(textfield_telefono_oficina.getText().equals("")){
                                JOptionPane.showMessageDialog(null,"Ingrese telefono de oficina");
                                textfield_telefono_oficina.requestFocus();
                                }else{  
                                    if(textfield_telefono_celular.getText().equals("")){
                                    JOptionPane.showMessageDialog(null,"Ingrese telefono celular");
                                    textfield_telefono_celular.requestFocus();
                                    }else{
                                        if(textfield_correo.getText().equals("")){
                                        JOptionPane.showMessageDialog(null,"Ingrese correo");
                                        textfield_correo.requestFocus();
                                        }else{
                                            if(textfield_observaciones.getText().equals("")){
                                            JOptionPane.showMessageDialog(null,"Ingrese observaciones");
                                            textfield_observaciones.requestFocus();
                                            }
                                            else{
                                                String observaciones2="";
                                                observaciones=textfield_observaciones.getText();
                                                
                                                try {
                                                    //llamar clase conexion
                                                    Conect= new Conexion();
                                                    ResultSet consulta = Conect.Consultar2("Contacto","Observaciones" , observaciones);
                                                    while(consulta.next()){
                                                        observaciones2=consulta.getString("Observaciones");
                                                    }
                                                   //insertarModificar();
                                                   // cargarTabla("");
                                                } catch (SQLException ex) {
                                                   JOptionPane.showMessageDialog(null,ex);
                                                }
                                                //nuevo
                                                /*if(accion.equals("Modificar")){
                                                
                                                }*/
                                                insertarModificar();
                                                /*if(observaciones.equals(observaciones2)){
                                                    JOptionPane.showMessageDialog(null,observaciones2+" ya existe");
                                                    //insertarModificar();
                                                }else{
                                                    insertarModificar();
                                                    //guardarImagenes();
                                                }*/
                                            }
                                        }
                                    
                                    }  
                                }
                            }
                        }
                    
                    }
                    
                }
            }
        }
    }//GEN-LAST:event_button_guardarActionPerformed
    
    private void cargarImagen(){
        observaciones=textfield_observaciones.getText();
        //Examinar fotos
        File archivo;
        JFileChooser abrirArchivo=new JFileChooser();
        abrirArchivo.setFileFilter(new FileNameExtensionFilter("Archivos de Imagen","jpg","png"));
        int respuesta = abrirArchivo.showOpenDialog(this);
        if(respuesta==JFileChooser.APPROVE_OPTION){
            archivo=abrirArchivo.getSelectedFile();
            urlOrigen=archivo.getAbsolutePath();
            Image foto= getToolkit().getImage(urlOrigen);
            foto=foto.getScaledInstance(145,175,1);
            //label_foto.setIcon(new ImageIcon(foto));
            extension =urlOrigen.substring(urlOrigen.lastIndexOf('.'));
            imgDestino ="C:\\Users\\Pablo\\Documents\\NetBeansProjects\\SISTEMA_FINAGOB\\src\\imagenes\\"+observaciones+extension;
        }
    }
        private void cargarDatos(String Id){
        try {
            Conect= new Conexion();
            ResultSet consulta =Conect.Consultar2("Contacto", "Id_Contacto", Id);
            //Recorre registros para mostrarlos
            while(consulta.next()){
                textfield_nombre.setText(consulta.getString("Nombre"));
                textfield_apellido.setText(consulta.getString("Apellido"));
                textfield_departamento.setText(consulta.getString("Departamento"));
                textfield_direccion.setText(consulta.getString("Direccion"));
                textfield_secretaria.setText(consulta.getString("Secretaria"));
                textfield_domicilio.setText(consulta.getString("Domicilio"));
                textfield_telefono_oficina.setText(consulta.getString("Telefono_oficina"));
                textfield_telefono_celular.setText(consulta.getString("Telefono_celular"));
                textfield_correo.setText(consulta.getString("Correo"));
                textfield_observaciones.setText(consulta.getString("Observaciones"));
                //imgbd=consulta.getString("Imagen");
                //mostrar imagen en label
                //Image foto= getToolkit().getImage(imgbd);
                //foto=foto.getScaledInstance(145,175,1);
                //label_foto.setIcon(new ImageIcon(foto));
                
                
            }
            
        } catch (SQLException ex) {
            
        }
    }
    
    private void table_consultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_consultaMouseClicked
        habilitar();
        int filas;
        String Id;
        accion="Modificar";
        filas= table_consulta.getSelectedRow();
        
        Id=(String)modelo.getValueAt(filas,0);
        //textfield_observaciones.setEnabled(false);
        id_actualizar =Id;
        cargarDatos(Id);
    }//GEN-LAST:event_table_consultaMouseClicked

    private void button_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_borrarActionPerformed
        System.out.println("Activacion de evento");
        if(JOptionPane.YES_NO_OPTION==JOptionPane.showConfirmDialog(null,"Desea eliminar los registros "+"'","Eliminar registros",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)){
            System.out.println("Previo a mensaje y deshabilitacion");
            String Nombre=textfield_nombre.getText();
            mensaje="Los datos se han eliminado";
            deshabilitar();
            try {
                Conect = new Conexion();
                PreparedStatement pst=Conect.Eliminar("Contacto", "Nombre", Nombre);
                JOptionPane.showMessageDialog(null, mensaje);
                cargarTabla("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }else{
            deshabilitar();
        }
    }//GEN-LAST:event_button_borrarActionPerformed

    private void textfield_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_buscarActionPerformed
        
    }//GEN-LAST:event_textfield_buscarActionPerformed

    private void textfield_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfield_buscarKeyReleased
        campoconsulta=String.valueOf(combobox_parametro.getSelectedItem());
        System.out.println("Campo a consultar= "+campoconsulta);
        cargarTabla(textfield_buscar.getText());
    }//GEN-LAST:event_textfield_buscarKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed
    //Metodo para deshabilitar controles
    public void deshabilitar(){
        observaciones=" ";
        accion="Insertar";
        urlOrigen=" ";
        //label_foto.setIcon(null);
        textfield_nombre.setEnabled(false);
        textfield_apellido.setEnabled(false);
        textfield_departamento.setEnabled(false);
        textfield_direccion.setEnabled(false);
        textfield_secretaria.setEnabled(false);
        textfield_telefono_oficina.setEnabled(false);
        textfield_telefono_celular.setEnabled(false);
        textfield_correo.setEnabled(false);
        textfield_observaciones.setEnabled(false);
        textfield_domicilio.setEnabled(false);
        
        textfield_nombre.setText("");
        textfield_apellido.setText("");
        textfield_departamento.setText("");
        textfield_direccion.setText("");
        textfield_secretaria.setText("");
        textfield_telefono_oficina.setText("");
        textfield_telefono_celular.setText("");
        textfield_correo.setText("");
        textfield_observaciones.setText("");
        textfield_buscar.setText("");
        textfield_domicilio.setText("");
        textfield_nombre.requestFocus();
        
        button_guardar.setEnabled(false);
        button_borrar.setEnabled(false);
        button_cancelar.setEnabled(false);
        //button_examinar.setEnabled(false);  
    }
    
    //Habilitar controles
    public void habilitar(){
        observaciones=" ";
        accion="Insertar";
        urlOrigen=" ";
        //label_foto.setIcon(null);
        
        textfield_nombre.setEnabled(true);
        textfield_apellido.setEnabled(true);
        textfield_departamento.setEnabled(true);
        textfield_direccion.setEnabled(true);
        textfield_secretaria.setEnabled(true);
        textfield_telefono_oficina.setEnabled(true);
        textfield_telefono_celular.setEnabled(true);
        textfield_correo.setEnabled(true);
        textfield_observaciones.setEnabled(true);
        textfield_domicilio.setEnabled(true);
        
        textfield_nombre.setText("");
        textfield_apellido.setText("");
        textfield_departamento.setText("");
        textfield_direccion.setText("");
        textfield_secretaria.setText("");
        textfield_telefono_oficina.setText("");
        textfield_telefono_celular.setText("");
        textfield_correo.setText("");
        textfield_observaciones.setText("");
        textfield_buscar.setText("");
        textfield_domicilio.setText("");
        textfield_nombre.requestFocus();
        
        button_guardar.setEnabled(true);
        button_borrar.setEnabled(true);
        button_cancelar.setEnabled(true);
        //button_examinar.setEnabled(true);
    }
    

    //Metodo para cargar tabla de registros
    public void cargarTabla(String valor){
        String[] titulos={"Id","Nombre","Apellido","Departamento","Direccion","Secretaria","Domicilio","Telefono_Oficina",
        "Telefono_Celular","Correo","Observaciones","Foto"};
        String[] registros= new String[12];
        modelo = new DefaultTableModel(null,titulos);
        try {
            //Mostrar registros en la tabla
            Conect = new Conexion();
            ResultSet consulta= Conect.Consultar1("Contacto",campoconsulta ,valor);
            while(consulta.next()){
                registros[0] = consulta.getString("Id_Contacto");
                registros[1] = consulta.getString("Nombre");
                registros[2] = consulta.getString("Apellido");
                registros[3] = consulta.getString("Departamento");
                registros[4] = consulta.getString("Direccion");
                registros[5] = consulta.getString("Secretaria");
                registros[6] = consulta.getString("Domicilio");
                registros[7] = consulta.getString("Telefono_oficina");
                registros[8] = consulta.getString("Telefono_celular");
                registros[9] = consulta.getString("Correo");
                registros[10] = consulta.getString("Observaciones");
                //registros[11] = consulta.getString("Imagen");
                modelo.addRow(registros);               
            }
            //Mostrar titulos de la tabla
            table_consulta.setModel(modelo);
            
        } catch (SQLException ex) {    
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_agregar;
    private javax.swing.JButton button_borrar;
    private javax.swing.JButton button_cancelar;
    private javax.swing.JButton button_guardar;
    private javax.swing.JComboBox combobox_parametro;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_consulta;
    private javax.swing.JTextField textfield_apellido;
    private javax.swing.JTextField textfield_buscar;
    private javax.swing.JTextField textfield_correo;
    private javax.swing.JTextField textfield_departamento;
    private javax.swing.JTextField textfield_direccion;
    private javax.swing.JTextField textfield_domicilio;
    private javax.swing.JTextField textfield_nombre;
    private javax.swing.JTextField textfield_observaciones;
    private javax.swing.JTextField textfield_secretaria;
    private javax.swing.JTextField textfield_telefono_celular;
    private javax.swing.JTextField textfield_telefono_oficina;
    // End of variables declaration//GEN-END:variables
}
